name: RoundsDownRange
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#adadad'
    - '#dbdbdb'
    - '#000000'
    - '#9c0818'
    - '#565656'
  brandStrength: 0.7100194513332099
  lightness: 0.16392245166935027
  saturation: 0.3237964112777263
  rhythmicContrast: 0.6878516399301589
purpose: []
